### ISSUE TITLE
How to use the nexus cargo registry with an actual Rust project ?

### ISSUE THREAD

**Issue by 2ndTaleStudio** [sonatype-nexus-community/nexus-repository-cargo#11]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Well I'm actually trying to use this plugin as described in the README.md in a local docker container. However, how it is supposed to be used with cargo? To provide a cargo crate registry you would maintain the `.cargo/config.toml` file with the registry like so:
```toml
[source.nexus]
registry = "http://localhost:8081/repository/cargo-hosted/"
```

However, this does not work. The reason - as far as I understand the structure of the crates.io repository is that the maintained URL should lead to a github repo containing the crates index. However the nexus URL does not lead to a github repo. Thus the attempt of cargo to access the registry fails with:

```
Updating `http://localhost:8081/repository/cargo-hosted/` index
warning: spurious network error (2 tries remaining): unexpected http status code: 404; class=Http (34)
warning: spurious network error (1 tries remaining): unexpected http status code: 404; class=Http (34)
```

As the actual documention is still `TBD` I'm wondering how this setup is intended to work.

* **What feature or behavior is this required for?**
I'm trying to use the nexus plugin to serve a company internal crates.io registry mirror/ internal crates host for our Rust projects.

* **How could we solve this issue? (Not knowing is okay!)**
Well, I'd appreciate a documentation how the setup of the crates registry served from nexus is intended to work.

* **Anything else?**
Is this project still actively maintained?

**Comment by gschulze** [comment]
From what I found out, your `config.toml `should look like this:

```toml
[net]
git-fetch-with-cli = true

[registries.nexus]
registry = "http://localhost:8081/repository/cargo-hosted/index"
```

You can use `curl` to obtain a token like this:

```
curl -X GET -u <username> http://localhost:8081/repository/cargo-hosted/token
```

Copy the token to '~/.cargo/credentials':

```
[registries.nexus]
token = "Bearer CargoRegistryBearerToken.<token>"
```

You should now be able to publish crates to your registry using `cargo publish --registry nexus`.

However, it seems that the project is not in a working state, since adding your published package as a dependency fails with `cargo` complaining that the dependency cannot be found. Seems like the index is not updated yet (WIP implementation in branch `index_generation`?).

Dear maintainers, are there any plans to have a working version soon? I'd be willing to contribute as well.

**Comment by gy0801151351** [comment]
I got an issue like this. Maybe they are because of the same reason.


Execution failed (exit code 101).
E:/Library_Store/Cargo/bin/cargo.exe metadata --verbose --format-version 1 --all-features
stdout :     Updating `http://10.2.4.210:8081/repository/crate-index/` index
     Running `git fetch --force --update-head-ok http://10.2.4.210:8081/repository/crate-index/ refs/heads/master:refs/remotes/origin/master HEAD:refs/remotes/origin/HEAD`
error: failed to get `smart_pointer` as a dependency of package `hello_rust_lib v0.1.0 (E:\Projects\Rust_Projects\hello_rust_lib)`

Caused by:
  failed to load source for dependency `smart_pointer`

Caused by:
  Unable to update registry `http://10.2.4.210:8081/repository/crate-index/`

Caused by:
  failed to fetch `http://10.2.4.210:8081/repository/crate-index/`

Caused by:
  process didn't exit successfully: `git fetch --force --update-head-ok http://10.2.4.210:8081/repository/crate-index/ refs/heads/master:refs/remotes/origin/master HEAD:refs/remotes/origin/HEAD` (exit code: 128)
  --- stderr
  fatal: repository 'http://10.2.4.210:8081/repository/crate-index/' not found

**Comment by mashintsev** [comment]
You can configure config.toml like this - https://gist.github.com/mashintsev/3e6ab7840d6233ab7932565d056b8158
